# frozen_string_literal: true

module MendixBridge
  class RubyInventoryGenerator
    def self.generate(inventory)
      inventory.modules.each_with_object({}) do |app_module, result|
        name = app_module.qualified_name
        elements = inventory.elements.select do |element|
          element.qualified_name&.start_with?("#{name}.") &&
            %w[entity association].include?(element.type)
        end
        next if elements.empty?

        result[name] = {
          "entities" => elements.select { |element| element.type == "entity" }.map { |element| serialize(element) },
          "associations" => elements.select { |element| element.type == "association" }.map { |element| serialize(element) }
        }
      end
    end

    def self.ruby_source(module_name, domain)
      namespace = module_name.gsub(/[^A-Za-z0-9_]/, "_")
      json = JSON.pretty_generate(domain)

      <<~RUBY
        # frozen_string_literal: true
        # Generated by mendix-ruby import. Changes will be replaced by refresh.

        require "json"

        module MendixGenerated
          module #{namespace}
            DOMAIN_MODEL = JSON.parse(<<~JSON)
        #{indent(json, 6)}
            JSON
          end
        end
      RUBY
    end

    def self.file_name(module_name)
      module_name
        .gsub(/([a-z\d])([A-Z])/, '\1_\2')
        .gsub(/[^A-Za-z0-9]+/, "_")
        .downcase
    end

    def self.serialize(element)
      {
        "name" => element.label,
        "qualified_name" => element.qualified_name,
        "details" => element.details
      }.compact
    end

    def self.indent(text, spaces)
      prefix = " " * spaces
      text.lines.map { |line| "#{prefix}#{line}" }.join
    end

    private_class_method :serialize, :indent
  end
end
